INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER,
EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C130', 'Anaya', 'Grewal', 'F', to_date('7-Apr-84', 'DD-MON-RR'), 6789432123, 'anaya.grewal@gmail.com', 40000, 'Service', 30000, 'HR Executive', 'IBM');


INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C103', 'Arun', 'Shabarwal', 'M', to_date('9-Sep-78', 'DD-MON-RR'), 8989234123, 'arun.s@gmail.com', 80000, 'Self-Employed', 40000, 'Play School Owner', NULL);

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C104', 'Mayank', 'Mittal', 'M', to_date('20-Jan-87', 'DD-MON-RR'), 8978654563, 'mayank.mittal@gmail.com', 120000, 'Self-Employed', 60000, 'Fitness Trainer', NULL);

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C105', 'Kiran', 'Jain', 'F', to_date('15-Aug-79', 'DD-MON-RR'), 8097652345, 'kiran.jain@gmail.com', 200000, 'Self-Employed', 80000, 'Chartered Accountant', NULL);

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C106', 'Sapna', 'Ranjan', 'F', to_date('12-Jun-80', 'DD-MON-RR'), 9997865432, 'sapna.ranjan@gmail.com', 80000, 'Service', 30000, 'HR Manager', 'Wipro');

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C107', 'Geetika', 'Kumari', 'F', to_date('2-Apr-89', 'DD-MON-RR'), 9011234568, 'geetika.kumari@gmail.com', 60000, 'Service', 25000, 'Sr. Software Engineer', 'IBM');

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C108', 'Puneet', 'Sharma', 'M', to_date('19-Dec-70', 'DD-MON-RR'), 8878654321, 'puneet.sharma@gmail.com', 75000, 'Service', 30000, 'DBA', 'TerraData');

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C109', 'Pooja', 'Agarwal', 'F', to_date('5-Oct-71', 'DD-MON-RR'), 7756789543, 'pooja.agarwal@gmail.com', 100000, 'Service', 35000, 'Technial Lead', 'IBM');

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C110', 'Sapan', 'Gupta', 'M', to_date('10-Apr-88', 'DD-MON-RR'), 7987654422, 'sapan.gupta@gmail.com', 90000, 'Self-Employed', 40000, 'Interior Designer', NULL);

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C111', 'Abhay', 'Singh', 'M', to_date('17-May-82', 'DD-MON-RR'), 8932457654, 'abhay.singh@gmail.com', 45000, 'Self-Employed', 15000, 'Graphic Designer', NULL);

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C112', 'Pulkit', 'Ahuja', 'M', to_date('11-Apr-72', 'DD-MON-RR'), 9911456743, 'pulkit.ahuja@gmail.com', 60000, 'Self-Employed', 20000, 'Content Writer', NULL);


Select * from LMS_customer_kushmakar;


INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C113', 'Manju', 'Sharma', 'F', to_date('13-Sep-72', 'DD-MON-RR'), 9999678954, 'manju.sharma@gmail.com', 125000, 'Service', 38000, 'Solution Consultant', 'Nucleus');

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C114', 'Snehal', 'Tiwari', 'F', to_date('26-Jan-74', 'DD-MON-RR'), 8769787654, 'snehal.tiwari@gmail.com', 100000, 'Service', 60000, 'Project Manager', 'Wipro');

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C115', 'Abhishek', 'Kumar', 'M', to_date('2-Oct-69', 'DD-MON-RR'), 8134567890, 'abhishek.kumar@gmail.com', 230000, 'Self-Employed', 80000, 'Event Planner', NULL);

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C116', 'Raj', 'Arora', 'M', to_date('10-Sep-90', 'DD-MON-RR'), 7895432123, 'raj.arora@gmail.com', 65000, 'Service', 25000, 'Sr. Software Engineer', 'HCL');

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C117', 'Pallavi', 'Joshi', 'F', to_date('12-Jun-89', 'DD-MON-RR'), 8765908921, 'pallavi.joshi@gmail.com', 40000, 'Service', 30000, 'Software Engineer', 'Infogain');

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C118', 'Surjit', 'Kaur', 'F', to_date('11-Mar-74', 'DD-MON-RR'), 8967885431, 'surjit.kaur@gmail.com', 125000, 'Service', 45000, 'Solution Consultant', 'HCL');

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C119', 'Karan', 'Singh', 'M', to_date('10-May-73', 'DD-MON-RR'), 8888675432, 'karan.singh@gmail.com', 70000, 'Self-Employed', 28000, 'Fitness Trainer', NULL);

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C120', 'Raman', 'Jaiswal', 'M', to_date('7-Jan-88', 'DD-MON-RR'), 9780006643, 'raman.jaiswal@gmail.com', 200000, 'Self-Employed', 70000, 'Event Planner', NULL);

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C121', 'Atif', 'Rana', 'M', to_date('18-Apr-87', 'DD-MON-RR'), 9124678901, 'atif.rana@gmail.com', 45000, 'Self-Employed', 30000, 'Digital Marketing', NULL);

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C122', 'Deepak', 'Kumar', 'M', to_date('15-Jun-76', 'DD-MON-RR'), 7089654321, 'deepak.kumar@gmail.com', 45000, 'Self-Employed', 20000, 'Digital Marketing', NULL);

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C123', 'Sneha', 'Raj', 'F', to_date('19-Nov-85', 'DD-MON-RR'), 9801345678, 'sneha.raj@gmail.com', 100000, 'Service', 40000, 'Technical Manager', 'Nucleus');

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C124', 'Bhavana', 'Sharma', 'F', to_date('25-Dec-84', 'DD-MON-RR'), 8674532789, 'bhavana.sharma@gmail.com', 100000, 'Service', 35000, 'Project Manager', 'TCS');

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C125', 'Bharati', 'Raheja', 'F', to_date('10-Dec-69', 'DD-MON-RR'), 9783452123, 'bharati.raheja@gmail.com', 95000, 'Service', 38000, 'DBA', 'TerraData');

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C126', 'Mamta', 'Kumari', 'F', to_date('11-Jan-76', 'DD-MON-RR'), 8567842314, 'mamta.kumari@gmail.com', 65000, 'Self-Employed', 40000, 'Freelance Developer', NULL);

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C127', 'Bhavay', 'Gupta', 'M', to_date('20-Aug-78', 'DD-MON-RR'), 9344123456, 'bhavay.gupta@gmail.com', 65000, 'Self-Employed', 30000, 'Freelance Developer', NULL);

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C128', 'Dhawal', 'Kishore', 'M', to_date('14-Apr-77', 'DD-MON-RR'), 8653358913, 'dhawal.kishore@gmail.com', 80000, 'Service', 30000, 'Technical Lead', 'Nucleus');

Select * from LMS_customer_kushmakar;

ROLLBACK TO A;

COMMIT;

UPDATE LMS_customer_kushmakar SET LAST_NAME = 'Sharma' WHERE CUSTOMER_ID = 'C103';

UPDATE LMS_customer_kushmakar SET PROFESSION= 'Service', DESIGNATION= 'Asst Manager',COMPANY_NAME = 'Wipro' WHERE CUSTOMER_ID = 'C104';

DELETE FROM LMS_customer_kushmakar WHERE TOTAL_MONTHLY_EXPENSE<40000;

DELETE FROM LMS_AGREEMENT_DTL_kushmakar WHERE LOAN_DISBURAL_DATE < 01-Jan- 2000;

COMMIT;

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, 
MONTHLY_INCOME, PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C129', 'Divya', 'Singh', 'F', to_date('16-May-84', 'DD-MON-RR'), 9999123456, 'divya.singh@gmail.com', 70000, 'Service', 28000, 'HR Manager', 'HCL');

INSERT INTO LMS_customer_kushmakar (CUSTOMER_ID, FIRST_NAME, LAST_NAME, GENDER, DATE_OF_BIRTH, CONTACT_NUMBER, EMAIL_ADDRESS, MONTHLY_INCOME, 
PROFESSION, TOTAL_MONTHLY_EXPENSE, DESIGNATION, COMPANY_NAME) 
VALUES ('C130', 'Anaya', 'Grewal', 'F', to_date('7-Apr-84', 'DD-MON-RR'), 6789432123, 'anaya.grewal@gmail.com', 40000, 'Service', 30000, 'HR Executive', 'IBM');

SAVEPOINT A;

DELETE FROM LMS_customer_kushmakar;