

--1. Create the table Customer based on the following instance chart.
CREATE TABLE LMS_CUSTOMER_M00(
Customer_ID  VARCHAR(20) NOT NULL,
First_Name  VARCHAR(20) NOT NULL,
Last_Name VARCHAR(20),
Gender  VARCHAR(1) NOT NULL,
Date_Of_Birth  DATE NOT NULL,
Contact_Number VARCHAR(10)  NOT NULL,
Email_Address  VARCHAR(40) NOT NULL,
Monthly_Income  NUMBER(8,2) NOT NULL,
Profession VARCHAR(40),
Total_Monthly_Expense  NUMBER(8,2) NOT NULL,
Designation VARCHAR(40),
Company_Name VARCHAR(40)
);

SELECT * FROM  LMS_CUSTOMER_M00;




--2. Create the table LoanProductCategory based on the following instance chart. 
CREATE TABLE LMS_PRODUCT_CATEGORY_M_kushmakar(
category_ID VARCHAR(10)  NOT NULL,
Category_Name  VARCHAR(50) NOT NULL,
Asset_Based VARCHAR (1)  NOT NULL check(Asset_based IN('Y','N')),
Description VARCHAR(150),
SecuredLoan  VARCHAR(2) NOT NULL, check(securedLoan in('S','US'))

);

SELECT * FROM LMS_PRODUCT_CATEGORY_M_kushmakar;

--3. Create the table LoanProduct based on the following instance chart. 

CREATE TABLE LMS_Product_M_kushmakar(
Product_Code  VARCHAR(20) NOT NULL,
Product_Name  VARCHAR(100) NOT NULL,
Product_Description VARCHAR(200),
Product_Category  VARCHAR(10) NOT NULL,
Max_Tenure Number(2),
Min_Tenure Number(2)
);

SELECT * FROM LMS_Product_M_kushmakar;


--4 Create the table Loan_Agreement based on the following instance chart. 

CREATE TABLE LMS_AGREEMENT_DTL_kushmakar(
Agreement_ID  VARCHAR(20) NOT NULL,
Lessee_ID  VARCHAR(100) NOT NULL,
Tenure Number(2),
ROI NUMBER(3,1),
Loan_Amount NUMBER(10,2),
Repayment_Frequency VARCHAR(2), 
Loan_Disbursal_Date DATE,
Status VARCHAR(10),
Product_Code VARCHAR(20) NOT NULL,
Constraint chk1234Kush check(Repayment_Frequency IN('M','Y','Q','HY')),
Constraint chk12345Kush check(Status IN('Pending','Approved', 'Rejected', 'Active', 'Closed'))
);

SELECT * FROM LMS_AGREEMENT_DTL_kushmakar;

--5. Create the table EMI_Schedule
CREATE TABLE  LMS_REPAYSCH_DTL_kushmakar(
Agreement_id  Varchar(20)NOT NULL,
PropInstID  Number(8)  GENERATED BY DEFAULT AS IDENTITY,
Installment_Amount  Number(8,2)NOT NULL,
Installment_Number Number(3) NOT NULL,
Principal_Component  Number(8,2) NOT NULL,
Interest_ComponentNumber Number(8,2) NOT NULL,
Balance_Principal_Amount  Number(8,2)NOT NULL,
Penalty_Charges Number(8,2),
Installment_Due_Date Date NOT NULL
);

SELECT * FROM LMS_REPAYSCH_DTL_kushmakar;

--6. Create the table Transaction_Type. 

CREATE TABLE LMS_TXNTYPE_M_kushmakar(
Txn_Type  VARCHAR(20) Not Null,
Description VARCHAR(100),
Constraint chk12345Kush1 check(Txn_Type IN('Installment', 'LPP '))
);

SELECT * FROM LMS_REPAYSCH_DTL_kushmakar;

--7. Create the table Advice.

CREATE TABLE LMS_TXN_ADVICE_DTL_kushmakar(
Txn_Advice_ID Number(8) GENERATED BY DEFAULT AS IDENTITY,
Adviceamt Number(8,2) Not Null,
AdviceDate  Date Not Null,
Case_Id  Varchar(20),
TxnID  Number(8) Not Null,
TxnType  Varchar(20) Not Null
);

SELECT * FROM  LMS_TXN_ADVICE_DTL_kushmakar;

--8. Create the table Payment. 

CREATE TABLE LMS_CHEQUE_DTL_kushmakar(
Cheque_Id  NUMBER(8) GENERATED BY DEFAULT AS IDENTITY,
Payment_Mode  VARCHAR(1) NOT NULL,
Cheque_Num  VARCHAR(50) NOT NULL,
Cheque_Date DATE,
Cheque_Amount NUMBER(10,2),
Drawn_On_Bank VARCHAR(50),
Deposit_Date DATE,
Status VARCHAR(1)

 check(Status IN('C' ,'D' ,'X' ,'R')),
 check(Cheque_Num  IN('Instrument')),
 check(Payment_Mode IN('C','Q','D','T'))
);
SELECT * FROM LMS_CHEQUE_DTL_kushmakar;



--9. Create the table Receipt_Allocation. 

CREATE TABLE LMS_PAYMENT_DTL_kushmakar(
Payment_ID  Number(8) unique not null,
Cheque_ID  Number(8) unique not null,
Payment_Date Date  NOT NULL,
Status  Varchar(1) NOT NULL check(Status IN('c','N')), 
Txn_Advice_Id  Number(8)NOT NULL
);

SELECT * FROM LMS_PAYMENT_DTL_kushmakar;
 
select * from user_tables where table_name like '%SQL_DAY1_ASSIGMENT%';





